services:
  postgres:
    image: postgres:16-alpine
    container_name: url_shortner_db
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: urlshortner
      POSTGRES_PASSWORD: urlshortner
      POSTGRES_DB: urlshortner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U urlshortner -d urlshortner"]
      interval: 5s
      timeout: 5s 
      retries: 5 
  app:
    build: .
    container_name: url_shortner_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://urlshortner:urlshortner@postgres:5432/urlshortner?sslmode=disable
    depends_on:
      - postgres
  
volumes:
  postgres_data: